### ISSUE TITLE
Не работает!

### ISSUE THREAD

**Issue by sergio-nsk** [alexrush1/ilovelabs#10]
https://github.com/alexrush1/ilovelabs/blob/709b49fd0e8a166b0d220359ae98fa8a6d72c0dc/Base64(Lab_8)/base64ed.c#L92

Вот такие байты во входном файле (11 байтов):
```
{0xC0, 0x69, 0x52, 0x0A, 0x01, 0xE9, 0x52, 0x3F, 0xDF, 0x00, 0x00}
```
кодируются неправильно в 14 байтов, а должно быть 16:
```
wGlSCgHpUj/fA=
```
А декодирование оставляет только 9 байт от исходных
```
{0xC0, 0x69, 0x52, 0x0A, 0x01, 0xE9, 0x52, 0x3F, 0xDF}
```

**Comment by alexrush1** [comment]
Странно, но я не могу поймать такой ошибки. Что именно вы пытались закодировать?
Попытка поработать с строкой:
    
    wGlSCgHpUj/fA=
Ни к чему не привела, я не смог понять, чем вы тестировали :D

**Comment by alexrush1** [comment]
Исправил, проблема в том, что я изначально не до конца (как оказалось) понимал алгоритм

**Comment by alexrush1** [comment]
Стоп, то есть вы во входной файл запихнули 0х00?

**Comment by alexrush1** [comment]
Вот теперь результат с двумя добавленными 0x00 0x00 
![Вот](https://i.ibb.co/7YgdXrH/input.png)

    Это то, что я передал программе

![](https://i.ibb.co/L9RWP6P/output.png)

    То, что получил после encode

![](https://i.ibb.co/4d1cZXz/decode.png)

   Результат после decode

**Comment by sergio-nsk** [comment]
Теперь давай избавляйся от ужасных повторений в коде.

**Comment by sergio-nsk** [comment]
Кто сказал, что параметры задаются в строгом порядке? Почему у тебя не работает программа так: a.out -f 60 -e ...?

**Comment by alexrush1** [comment]
Вы, сейчас, наверное удивитесь. Но на первой паре оба в этом семестре я спрашивал у вас про порядок, Артём тоже. Вы ответили, что разный порядок не нужен
