### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by sergio-nsk** [alexrush1/ilovelabs#13]
https://github.com/alexrush1/ilovelabs/blob/cb508c8ece3c2426f0fe847903e67cf42d5a8d91/Lab_12%20(Kryskal)/kryskal.c#L163

`free(buf)` где?

**Comment by alexrush1** [comment]
оооой, это что-то совсем уже грустно:с

**Comment by sergio-nsk** [comment]
Теперь даже не компилируется.

**Comment by alexrush1** [comment]
Странно
Перепишу с нуля тогда

**Comment by alexrush1** [comment]
Хотя я может просто не все изменения кинул

**Comment by alexrush1** [comment]
Конечно, не все изменения ушли.

**Comment by alexrush1** [comment]
Можно узнать: чем вы компилируете программы? Мой компилятор вообще ни на что не ругается и не ругался

**Comment by alexrush1** [comment]
И всегда всё спокойно собирал

**Comment by alexrush1** [comment]
И собирает

**Comment by sergio-nsk** [comment]
Ни один компилятор не соберёт твою программу. Посмотри на область видимости переменной `buf`.

**Comment by alexrush1** [comment]
Только что Visual Studio три раза подряд собрала

**Comment by sergio-nsk** [comment]
Не известно, что она смотрела. То, что на гитхабе, она не соберёт.

**Comment by alexrush1** [comment]
Так
Не с той ветки взял

**Comment by alexrush1** [comment]
Ладно, буду с этим позже разбираться
Занимаюсь немного другим предметом

**Comment by alexrush1** [comment]
Починено
