### ISSUE TITLE
Медленно

### ISSUE THREAD

**Issue by sergio-nsk** [alexrush1/ilovelabs#6]
https://github.com/alexrush1/ilovelabs/blob/ecbdb77488cb3333f5b6bf3caa33b9e059bc2bf6/Lab_3/Lab3.c#L12

Не укладывается в 2 сек в последнем тесте. Во всём виновата `getc`.

**Comment by alexrush1** [comment]
Мой ультратупёжный ноутбук создавал большой файл 10 секунд, благодаря чему на тест давалось 20 секунд и он успевал пройтись:D 
Попробую оптимизировать

**Comment by alexrush1** [comment]
Похоже, что он у меня и не то, и не то:D
